//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLKMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyLinhKienMT
    {
        public int STT { get; set; }
        public string LoaiLinhKien { get; set; }
        public string ThuongHieu { get; set; }
        public string TenLinhKien { get; set; }
        public string DungLuong { get; set; }
        public string KichThuoc { get; set; }
        public string BusRAM { get; set; }
        public string ChuanBoNho { get; set; }
        public string Chipset { get; set; }
        public int GiaBan { get; set; }
        public string TinhTrangKho { get; set; }
        public string ThoiHanBaoHanh { get; set; }
        public string GhiChu { get; set; }
    }
}
